/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  saveFile: [
    'save-file/save-file-introduction',
    'save-file/memory-card',
    {
      type: 'category',
      label: 'Quest Log',
      collapsed: false,
      items: [
        'save-file/quest-log/introduction',
        'save-file/quest-log/contents',
        {
          type: 'category',
          label: 'Player',
          items: [
            'save-file/quest-log/player/player-status-a',
            'save-file/quest-log/player/player-status-b',
            'save-file/quest-log/player/horse-place',
            'save-file/quest-log/player/player-return-place',
            'save-file/quest-log/player/player-field-last-stay-info',
            'save-file/quest-log/player/player-last-mark-info',
            'save-file/quest-log/player/player-item',
            'save-file/quest-log/player/player-get-item',
            'save-file/quest-log/player/player-item-record',
            'save-file/quest-log/player/player-item-max',
            'save-file/quest-log/player/player-collect',
            'save-file/quest-log/player/player-wolf',
            'save-file/quest-log/player/light-drop',
            'save-file/quest-log/player/letter-info',
            'save-file/quest-log/player/fishing-info',
            'save-file/quest-log/player/player-info',
            'save-file/quest-log/player/player-config',
          ],
        },
      ],
    },
  ],
  technicalExplanations: [
    // { type: 'autogenerated', dirName: './technical-explanations' },
    { type: 'autogenerated', dirName: 'technical-explanations' },
  ],
  rando: [{ type: 'autogenerated', dirName: 'rando' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
